env:
  DOCKER_REGISTRY_URL: 192.168.56.12:5000
  DOCKER_IMAGE_NAME: task-manager-frontend

name: Task Manager Frontend Image
run-name: ${{ gitea.actor }} is building the Frontend image
on:
  push:
    branches: [main]
    paths:
      - 'services/frontend/**' # The whole pipeline only runs if this folder changes
  # Also allows manual triggering for demos
  workflow_dispatch:

jobs:
  test-logic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.20.0'

      - name: Install dependencies
        run: |
          cd services/frontend/test
          npm install

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image for testing
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          context: ./services/frontend
          file: ./services/frontend/Dockerfile
          push: false
          load: true
          tags: task-manager-frontend:test

      - name: Run Frontend container
        run: |
          docker run -d -p 80:80 --name frontend-test task-manager-frontend:test
          sleep 2

      - name: Run Smoke Tests
        run: |
          cd services/frontend/test
          bash smoke_test.sh

      - name: Run Playwright E2E Tests
        run: |
          cd services/frontend/test
          npx playwright test test_ui.spec.js

      - name: Stop and remove container
        if: always()
        run: |
          docker stop frontend-test || true
          docker rm frontend-test || true

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-results
          path: services/frontend/test/test-results/

  build-images:
    needs: test-logic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-config-inline: |
            [registry."192.168.56.12:5000"]
              http = true
              insecure = true

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_REGISTRY_URL }}/${{ env.DOCKER_IMAGE_NAME }}
          tags: |
            type=sha,enable=true,priority=100,prefix=,suffix=,format=short
            type=raw,value=latest,enable={{is_default_branch}}
        env:
          DOCKER_METADATA_SHORT_SHA_LENGTH: 10

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          context: ./services/frontend
          file: ./services/frontend/Dockerfile
          provenance: mode=max
          sbom: true
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
